# fly.toml app configuration file generated for red-discordbot on 2025-06-01T19:23:30+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'red-discordbot'
primary_region = 'sin'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
